name: Post welcome comment
on:
  pull_request:
  types: [opened]
jobs:
  build:
    name: Post welcome comment
    runs-on: unbuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
